### ISSUE TITLE
Specify joints

### ISSUE THREAD

**Issue by GeorgyOstr** [stephane-caron/openrave_models#3]
Hi, thanks a lot.
I have my model in blender now, and I can even export it from .wrl to .dae!

But all my joints seems to be independent and when I export I get one solid mesh instead
of robot with dependent joints.

So my question is: how to prepare the model to be exported in to right .dae.
How to specify all joints and constraints?

All joints in my model are going to be rotational, there should be some limits,
but that is kind of optional.  

![screenshot from 2017-07-08 19-11-14](https://user-images.githubusercontent.com/17079559/27987128-bb56c858-6411-11e7-9ea1-62fd1022c44a.png)

**Comment by stephane-caron** [comment]
Yes, VRML meshes are always loaded as a single big rigid body. In your case, you should:
- Export your meshes link by link: ``Link1.wrl``, ``Link2.wrl``, etc.
- Load each of these meshes from a robot spec written in [OpenRAVE XML format](http://openrave.programmingvision.com/wiki/index.php/Format:XML), where you can also specify your joints, joint limits, etc.
- Load your robot's XML from an ``openravepy.Environment`` object.

Happy rendering ;)
